<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputinput-box-otp</name>
   <tag></tag>
   <elementGuidId>4dd6c497-862f-4186-b256-6f85027c5836</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-box-otp</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-box-otp']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>422e9618-fe4d-4992-8e70-50075668f224</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>2a28bac3-e4d2-4b59-8b32-d4b43d7a9301</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>0cbb4b04-e8e4-4ea0-82d7-ecdea03a5b93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-box-otp</value>
      <webElementGuid>e29e37f6-322b-4ddc-a09a-bf5f23abb957</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d7d8e387-6af6-490f-b41e-2f535eae7780</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9001463d-7af8-4832-96a7-f41671da92df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-input-text cvf-widget-input cvf-widget-input-code single-input-box-otp</value>
      <webElementGuid>8e36789b-665a-435f-a610-04052c61c930</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-box-otp&quot;)</value>
      <webElementGuid>255182ad-6d0d-4a06-a21a-0785aa7bc196</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-box-otp']</value>
      <webElementGuid>420a48f7-131a-40b8-a0c4-122337edf967</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cvf-input-code']/span/div/input</value>
      <webElementGuid>64112589-b2ce-4433-8cb9-5bba59550e30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>ecd76298-1488-484b-bcee-3e3e6add7b6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @id = 'input-box-otp']</value>
      <webElementGuid>c7172e30-fca8-41ef-b743-8edee3138e40</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
