<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Sign in</name>
   <tag></tag>
   <elementGuidId>49d1a933-9a3e-454f-945a-2e3270360286</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#auth-signin-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='auth-signin-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>697884dd-631e-414f-b643-57bed56bf281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>auth-signin-button</value>
      <webElementGuid>7838e76c-00dd-4778-b412-f7b40b900fc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button a-button-span12 a-button-primary auth-disable-button-on-submit</value>
      <webElementGuid>a79ef70e-3d70-48e3-8f3a-85ce8044509a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            Sign in
          </value>
      <webElementGuid>e8bde903-4df7-4a20-bfc5-81ee7d962ae0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;auth-signin-button&quot;)</value>
      <webElementGuid>c33d89fc-84b5-435d-8a4a-12b5a5bcb5a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='auth-signin-button']</value>
      <webElementGuid>3f25d7ad-8ddc-4ca6-97e3-f4967918c2e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='authportal-main-section']/div[2]/div/div[2]/div/form/div/div[2]/span</value>
      <webElementGuid>671ca621-f034-4f32-bf65-1fb1ae197763</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span</value>
      <webElementGuid>7dea093f-847e-4222-b3b3-4ae5e5c16b1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'auth-signin-button' and (text() = '
            Sign in
          ' or . = '
            Sign in
          ')]</value>
      <webElementGuid>096c2aa5-4167-42a2-8a21-042b1fc33111</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
