<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_nav-categ-image</name>
   <tag></tag>
   <elementGuidId>46ffe9a5-7b03-4ee1-aa94-44796d75aa2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='nav-subnav']/a/span/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.nav-categ-image</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>83b99031-6aaf-4574-b132-9a73644caa79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://m.media-amazon.com/images/G/31/IMG17/Fashion/January/Ingresses/Subnav/Amazon-fashion-logo._CB485923938_.png</value>
      <webElementGuid>485c48a6-d617-4d91-be4b-df6ba5c37dc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-categ-image</value>
      <webElementGuid>d715e0ba-bf8e-47b3-994b-957dad766004</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Amazon Fashion</value>
      <webElementGuid>985732ed-f8fd-4461-8e8a-ec7ae4deaac7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-subnav&quot;)/a[@class=&quot;nav-a nav-hasImage&quot;]/span[@class=&quot;nav-a-content&quot;]/img[@class=&quot;nav-categ-image&quot;]</value>
      <webElementGuid>2fb8654b-e822-4693-ad25-e6593aff3e5b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-subnav']/a/span/img</value>
      <webElementGuid>fad7fac4-31bf-4d39-96db-3d420bb2e0c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Amazon Fashion']</value>
      <webElementGuid>df588973-c0cc-44f4-adcb-1d349b2488a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/img</value>
      <webElementGuid>56cf7a11-0e6b-42b6-b676-add38d13a5a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://m.media-amazon.com/images/G/31/IMG17/Fashion/January/Ingresses/Subnav/Amazon-fashion-logo._CB485923938_.png' and @alt = 'Amazon Fashion']</value>
      <webElementGuid>aeada861-313f-40b6-b336-0dfd588be1bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
