<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Sign in</name>
   <tag></tag>
   <elementGuidId>2894bb2a-8512-4eba-8b99-9b77c5beeadf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#auth-signin-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='auth-signin-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d8ea342c-0286-4cb3-9f42-c1b036141a19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>auth-signin-button</value>
      <webElementGuid>b3acea60-a31f-4784-b264-c908e6ad2963</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button a-button-span12 a-button-primary auth-disable-button-on-submit</value>
      <webElementGuid>7a5c2200-5541-477a-92bf-dda50dda0c74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            Sign in
          </value>
      <webElementGuid>ddc7fbfc-da60-4389-83e5-02ca934c8228</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;auth-signin-button&quot;)</value>
      <webElementGuid>4d4582e8-b004-47c6-95ae-3bc1b15af73a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='auth-signin-button']</value>
      <webElementGuid>14d50031-837c-42bf-97c7-92508fe0326c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='authportal-main-section']/div[2]/div/div[2]/div/form/div/div[2]/span</value>
      <webElementGuid>a7476944-0084-46fc-a20f-8822dfa56e99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span</value>
      <webElementGuid>01426580-3623-42d6-828c-44df1a710977</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'auth-signin-button' and (text() = '
            Sign in
          ' or . = '
            Sign in
          ')]</value>
      <webElementGuid>018719bf-c37b-4f4f-9a20-b5057ebd773e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
