<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_password</name>
   <tag></tag>
   <elementGuidId>92b602f8-1ed8-4dea-91a7-570dabfdb537</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ap_password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ap_password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>adbbd097-1828-4e94-8590-8011b4d833ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>02a92ecd-6026-4f69-bc4f-56f65e98c959</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1024</value>
      <webElementGuid>ce65376f-14cf-412e-9b4a-ca77c72429e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ap_password</value>
      <webElementGuid>347608a9-8905-4553-89d9-71de7bace829</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>0603277b-b9bb-40b1-bcab-0281df5072f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>bae62592-83df-46f8-abb0-5ddaa0e27236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-input-text a-span12 auth-autofocus auth-required-field</value>
      <webElementGuid>8edd74cd-a8be-4552-86a5-b2b7a184cead</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ap_password&quot;)</value>
      <webElementGuid>97f1b319-510c-411c-b1cf-44fb45d2bdf5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ap_password']</value>
      <webElementGuid>9d56c07e-b283-4097-9c5f-bba338cbaad7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='authportal-main-section']/div[2]/div/div[2]/div/form/div/div/input</value>
      <webElementGuid>69981230-cb24-4f4b-b652-b547f8ff6ef2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>d4cdf608-40e2-4cc6-9a78-62bfcdb2b8ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'ap_password' and @name = 'password']</value>
      <webElementGuid>15152639-587c-48bc-9664-0415f773d461</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
