<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Sign in</name>
   <tag></tag>
   <elementGuidId>80312375-8e85-436f-8dad-163c828b2ea1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#auth-signin-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='auth-signin-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5933a2c3-7a9a-493d-9438-65dc92927419</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>auth-signin-button</value>
      <webElementGuid>054f068b-911f-48dc-a0d1-535a1d837db3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button a-button-span12 a-button-primary auth-disable-button-on-submit</value>
      <webElementGuid>2bfa57de-add8-4841-b388-8f7f74993ce6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            Sign in
          </value>
      <webElementGuid>19d4977f-a283-4e5c-b2da-1ee4ffbf4167</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;auth-signin-button&quot;)</value>
      <webElementGuid>b42c1372-59fb-4e91-a14e-f5180f1ab39e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='auth-signin-button']</value>
      <webElementGuid>9a3eb70b-1908-41ef-a979-45872e2cd88d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='authportal-main-section']/div[2]/div/div[2]/div/form/div/div[2]/span</value>
      <webElementGuid>ad858bc7-4d73-48a3-a025-5602ffd05efc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span</value>
      <webElementGuid>9c5e3194-bdf0-4308-bc4d-88f471427cb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'auth-signin-button' and (text() = '
            Sign in
          ' or . = '
            Sign in
          ')]</value>
      <webElementGuid>c9a8b2d2-c61c-48a8-b935-3de048c87933</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
