<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Back to top</name>
   <tag></tag>
   <elementGuidId>e8a650a1-d879-4c5b-9c06-31c2ef6a4e05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.navFooterBackToTopText</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='navBackToTop']/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c9e7bfe8-93d1-42eb-a8cf-bb4adabe8f38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>navFooterBackToTopText</value>
      <webElementGuid>bd42e821-4155-42a6-a4f9-fd1d156b99a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
    Back to top
  </value>
      <webElementGuid>6419c554-5325-40c4-8066-294989c7ebc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navBackToTop&quot;)/div[@class=&quot;navFooterBackToTop&quot;]/span[@class=&quot;navFooterBackToTopText&quot;]</value>
      <webElementGuid>a6dc8011-5b05-479f-bf17-4f4f9b4992f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='navBackToTop']/div/span</value>
      <webElementGuid>a3f8c371-2a78-41aa-9e13-85edce02dd3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a/div/span</value>
      <webElementGuid>6907a238-9292-4b60-a124-d90974d3b07f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '
    Back to top
  ' or . = '
    Back to top
  ')]</value>
      <webElementGuid>0b85f9e8-eb7c-43ec-96dc-ca560ce8d7e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
