<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ppw-instrumentRowSelection_1</name>
   <tag></tag>
   <elementGuidId>3ca3de11-1842-4321-9719-b3e00289bec6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pp-7Pqs4I-123</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pp-7Pqs4I-123']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>035fd72a-bba9-440e-9401-ca3424898eaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pp-7Pqs4I-123</value>
      <webElementGuid>f291f8a0-cf64-4294-a6c8-146594489788</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>aed1c98d-e1d4-4de1-8ffb-522c41b71020</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ppw-instrumentRowSelection</value>
      <webElementGuid>7205c6bf-1bd7-4db2-b15e-a82bd8f5e591</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>instrumentId=amzn1.pm.poa.YW16bjEucG9hOmFtem4xLnBvYS5wb2RhLlVuaWZpZWRQYXltZW50c0ludGVyZmFjZTox.QTM0QzhDSTFQMTExSEE&amp;isExpired=false&amp;paymentMethod=UnifiedPaymentsInterface&amp;tfxEligible=false</value>
      <webElementGuid>e2041e22-2d50-4129-b67e-1ea241047824</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pp-7Pqs4I-123&quot;)</value>
      <webElementGuid>fa9049d4-91f8-4fcf-b9d8-c251d8b12c4d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pp-7Pqs4I-123']</value>
      <webElementGuid>e07a08e4-76a2-4f90-8a60-cbe3bde702a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pp-7Pqs4I-122']/div/div/div/div/div/div/label/input</value>
      <webElementGuid>ee4ced60-6ee5-44a1-aeec-8990408bce08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/label/input</value>
      <webElementGuid>a44a3129-1624-4194-a540-330c0c931f35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'pp-7Pqs4I-123' and @type = 'radio' and @name = 'ppw-instrumentRowSelection']</value>
      <webElementGuid>5bc3e1df-bdb8-453f-afdc-041d630436b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
