<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ppw-instrumentRowSelection</name>
   <tag></tag>
   <elementGuidId>2e024a54-b7c4-46d3-a136-d18ca4296ab3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pp-7Pqs4I-128</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pp-7Pqs4I-128']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b06274f0-50a7-42d5-a894-212dee288a99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pp-7Pqs4I-128</value>
      <webElementGuid>b4c02123-5446-431b-a88d-f5d4a1119948</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>56b55867-6f43-4cc2-a55b-990e7f78a0ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ppw-instrumentRowSelection</value>
      <webElementGuid>8df008f1-faa6-438f-8abe-60019e1099cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>instrumentId=EMI&amp;isExpired=false&amp;paymentMethod=CC&amp;tfxEligible=false</value>
      <webElementGuid>03529096-a959-4a0c-9229-8aa432e93422</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pp-7Pqs4I-128&quot;)</value>
      <webElementGuid>dab7c8eb-3704-4433-aff4-0557cf7b8da9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pp-7Pqs4I-128']</value>
      <webElementGuid>15125a78-79b6-450a-b563-0f5187600688</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pp-7Pqs4I-127']/div/div/div/div/span/div/label/input</value>
      <webElementGuid>ca5a770a-5d36-4bcb-a10d-a42074e458bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/span/div/label/input</value>
      <webElementGuid>47d5020d-8cc6-4eda-86ba-6bf1656ac6be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'pp-7Pqs4I-128' and @type = 'radio' and @name = 'ppw-instrumentRowSelection']</value>
      <webElementGuid>0a40316b-403d-4099-9c98-5d4350d8d8ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
