<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ppw-instrumentRowSelection_1_2</name>
   <tag></tag>
   <elementGuidId>42c0889b-7d6f-4e5c-9243-92d0bd9cf907</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pp-7Pqs4I-97</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pp-7Pqs4I-97']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b86cba7e-0c98-4aaa-9ec6-9f26d0c51872</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pp-7Pqs4I-97</value>
      <webElementGuid>e7514385-4ea0-4933-b22a-32c088f93410</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>b5c20223-d6bc-44b1-ab3e-6b5a0d52e94f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ppw-instrumentRowSelection</value>
      <webElementGuid>7ccb633a-d53d-4c16-8895-c9ce8ecf10f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>SelectableAddCreditCard</value>
      <webElementGuid>46ce4940-19c8-4561-b2eb-876b1a6d3648</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pp-7Pqs4I-97&quot;)</value>
      <webElementGuid>cc67009c-96bb-4f77-a8dd-5bfcc95d1adf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pp-7Pqs4I-97']</value>
      <webElementGuid>f6eb7faa-0b3e-4b6e-8de4-e22e7f9d8f52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pp-7Pqs4I-96']/div/div/div/div/div/span/div/label/input</value>
      <webElementGuid>2560616c-3297-4021-848e-0cc429e1c9ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>75d25a99-2190-4d11-afdf-09efe3a69e23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'pp-7Pqs4I-97' and @type = 'radio' and @name = 'ppw-instrumentRowSelection']</value>
      <webElementGuid>a846f552-04b8-4460-a3f5-82b2d917888b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
