<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_submit.delete.3c28bbc2-6709-40da-a37c_5ae046</name>
   <tag></tag>
   <elementGuidId>9ec47878-54d0-44ad-b5fb-3bd17c89eb6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;submit.delete.3c28bbc2-6709-40da-a37c-139d6af24ad6&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='submit.delete.3c28bbc2-6709-40da-a37c-139d6af24ad6']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c310487f-9ed4-4528-82c3-5ba4c3d275c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>submit.delete.3c28bbc2-6709-40da-a37c-139d6af24ad6</value>
      <webElementGuid>17bb0293-80c6-4edd-9161-d7e5bff6a2d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Delete</value>
      <webElementGuid>42dbe11e-5d85-415f-878c-ae6ae371f885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action</name>
      <type>Main</type>
      <value>delete</value>
      <webElementGuid>9b61f559-9d68-4cf9-8619-f2863cd419b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Delete Park Avenue Men&amp;#39;s Flat Front Smart Fit Dark Blue Formal Trouser</value>
      <webElementGuid>14307c84-03e8-43e5-b72c-cb76882191fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>f583afa9-09fa-4611-95cd-e9aae2113b73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-color-link</value>
      <webElementGuid>b9d4f355-8128-4059-a16a-1715014ac570</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sc-active-3c28bbc2-6709-40da-a37c-139d6af24ad6&quot;)/div[@class=&quot;sc-list-item-content&quot;]/div[@class=&quot;a-row a-grid-vertical-align a-grid-top sc-list-item-content-inner&quot;]/div[@class=&quot;sc-item-content-group&quot;]/div[@class=&quot;a-row sc-action-links&quot;]/span[@class=&quot;a-size-small sc-action-delete&quot;]/span[@class=&quot;a-declarative&quot;]/input[@class=&quot;a-color-link&quot;]</value>
      <webElementGuid>eecdc82c-5127-4311-8141-9150af7a4677</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='submit.delete.3c28bbc2-6709-40da-a37c-139d6af24ad6']</value>
      <webElementGuid>f087d87d-d6c1-4bc4-8c44-de43c4cfdbe2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sc-active-3c28bbc2-6709-40da-a37c-139d6af24ad6']/div[4]/div/div[3]/div/span[2]/span/input</value>
      <webElementGuid>046c5879-0355-4875-bbf5-7e5d11639cdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/span/input</value>
      <webElementGuid>48393d8f-6262-4c88-9315-f0ddee904049</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'submit.delete.3c28bbc2-6709-40da-a37c-139d6af24ad6' and @type = 'submit']</value>
      <webElementGuid>c0c9ae14-f0d5-48f2-af36-aecbf2b8ba5e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
