<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_submit.delete.74e5e150-dfed-4ef6-9522_931099</name>
   <tag></tag>
   <elementGuidId>5d3b6870-bd2e-4da0-8e0e-4ea3603239e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;submit.delete.74e5e150-dfed-4ef6-9522-076a17dbbd1c&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='submit.delete.74e5e150-dfed-4ef6-9522-076a17dbbd1c']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8197d1e0-de05-49a0-9f37-e0f8bedb6986</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>submit.delete.74e5e150-dfed-4ef6-9522-076a17dbbd1c</value>
      <webElementGuid>31ee100c-c5bd-4c07-b65e-c60e827da984</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Delete</value>
      <webElementGuid>3fb7c506-d4af-4b2f-9715-e325b70c707a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action</name>
      <type>Main</type>
      <value>delete</value>
      <webElementGuid>46c3541c-ea7b-424b-912c-7854fe5bb011</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Delete B &amp;amp; B Agro Products Chakravyuha Fruit Fly Trap Contains 2 Trap and 2 Lures</value>
      <webElementGuid>f4cd80dd-5fa3-4b8b-a8a7-db903906bdbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>f650b07f-76a2-4339-abc7-09548fd5de46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-color-link</value>
      <webElementGuid>8eeedc35-c838-4868-abb4-90e3a44d3b18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sc-active-74e5e150-dfed-4ef6-9522-076a17dbbd1c&quot;)/div[@class=&quot;sc-list-item-content&quot;]/div[@class=&quot;a-row a-grid-vertical-align a-grid-top sc-list-item-content-inner&quot;]/div[@class=&quot;sc-item-content-group&quot;]/div[@class=&quot;a-row sc-action-links&quot;]/span[@class=&quot;a-size-small sc-action-delete&quot;]/span[@class=&quot;a-declarative&quot;]/input[@class=&quot;a-color-link&quot;]</value>
      <webElementGuid>a38927b3-e414-49a4-a57a-19934abc9a19</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='submit.delete.74e5e150-dfed-4ef6-9522-076a17dbbd1c']</value>
      <webElementGuid>4b60ea4d-40c9-4747-87e4-402e2acbfc0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sc-active-74e5e150-dfed-4ef6-9522-076a17dbbd1c']/div[4]/div/div[3]/div/span[2]/span/input</value>
      <webElementGuid>7894e3ff-d596-4c58-bbe8-f9f7613ecd5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/span/input</value>
      <webElementGuid>16e834d7-4ee0-4197-b134-532de1c4dc71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'submit.delete.74e5e150-dfed-4ef6-9522-076a17dbbd1c' and @type = 'submit']</value>
      <webElementGuid>ddedd3bf-5366-4019-887d-5de18495de2b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
