<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Newest Arrivals</name>
   <tag></tag>
   <elementGuidId>865e9703-7bb9-4fc2-9ff8-0aedd566c639</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#s-result-sort-select_4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='s-result-sort-select_4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>eb93baa1-57d4-400e-b1dd-bb1c1f3fc9bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>43df1d95-2865-43b0-9614-721a0af654f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>43aa59e1-8d9d-4a53-a87d-2a7e7dd67f1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7b2b0e75-02f1-4635-9724-eb7a97bf84b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>{&quot;stringVal&quot;:&quot;date-desc-rank&quot;}</value>
      <webElementGuid>33f6bb91-4f1b-4158-989e-908ba9176b95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>s-result-sort-select_4</value>
      <webElementGuid>274f093f-3be0-4ed8-b9ac-2815561be225</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-dropdown-link</value>
      <webElementGuid>e9577450-e5a9-4794-a378-54bcccfb961c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Newest Arrivals</value>
      <webElementGuid>17c7cbd9-124b-451f-a99a-38a558d53716</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;s-result-sort-select_4&quot;)</value>
      <webElementGuid>9573b4c0-6ee9-4236-a349-41c9a460044f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='s-result-sort-select_4']</value>
      <webElementGuid>53cd8439-1958-4bcd-a6bc-2d2c077fdcd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='a-popover-2']/div/div/ul/li[5]/a</value>
      <webElementGuid>cdde0f5e-4e89-498b-89bd-b3a1fef213dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Newest Arrivals')]</value>
      <webElementGuid>75679521-2808-4882-93bd-06e8eaf892d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[92]</value>
      <webElementGuid>2ad09891-43c3-477c-85da-1080af038ce8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/ul/li[5]/a</value>
      <webElementGuid>1d0e8e6b-2a8f-4d38-9bcf-a699e6cc5a90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and @id = 's-result-sort-select_4' and (text() = 'Newest Arrivals' or . = 'Newest Arrivals')]</value>
      <webElementGuid>a526353f-a2d1-4d16-b47e-787d619887dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
