<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Go to Cart</name>
   <tag></tag>
   <elementGuidId>da259ab6-4a3b-42ee-8f3b-0fb7d43a0dac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sw-gtc > span.a-button-inner > a.a-button-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='sw-gtc']/span/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>236beead-5728-4f84-83e8-de7852c8e96d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/cart?ref_=sw_gtc</value>
      <webElementGuid>667467bb-da0e-4941-a498-0405d6002508</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-content-id</name>
      <type>Main</type>
      <value>sw-gtc_CONTENT</value>
      <webElementGuid>6208a5e8-bf51-44b0-9ceb-d04b2d25c5fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-slot-id</name>
      <type>Main</type>
      <value>sw-gtc</value>
      <webElementGuid>9fc9fcda-2b7f-4716-9997-6d4b8b0071df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8cd11668-77d4-4271-bd98-95ceac7c399d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-text</value>
      <webElementGuid>adff1d81-d4da-42b7-ac61-3f04e6e9c699</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-id</name>
      <type>Main</type>
      <value>cew029-5139uf-f464up-husg8n</value>
      <webElementGuid>5001d723-d12b-4ab9-a7fb-55b4fcd86514</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
    Go to Cart
</value>
      <webElementGuid>de08a935-cce2-494a-8fd8-617cb9283b71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sw-gtc&quot;)/span[@class=&quot;a-button-inner&quot;]/a[@class=&quot;a-button-text&quot;]</value>
      <webElementGuid>d97d0fad-f93b-4595-b3d4-c70d2a7799b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='sw-gtc']/span/a</value>
      <webElementGuid>25784671-9b1d-4963-b058-dab9a0e9df4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Go to Cart')])[2]</value>
      <webElementGuid>900aad1a-8107-4fe3-ad85-2e8a34bcdfd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/cart?ref_=sw_gtc')]</value>
      <webElementGuid>e661215c-b83c-4624-9563-ec1731ec3b42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/span/span/a</value>
      <webElementGuid>8f5dbfd2-88f9-4832-8919-75283fe892df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/cart?ref_=sw_gtc' and (text() = '
    Go to Cart
' or . = '
    Go to Cart
')]</value>
      <webElementGuid>3d61ffb9-60a5-4cb8-8632-e006444ba35e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
