<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>aattach-close_sideSheet-link</name>
   <tag></tag>
   <elementGuidId>696d7320-2f78-45ca-8226-23c03e012a88</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#attach-close_sideSheet-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='attach-close_sideSheet-link']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3aeb66a9-ff6a-4c13-9dcc-abf910b427e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>attach-close_sideSheet-link</value>
      <webElementGuid>7c2d1cb9-b41c-48b8-b067-2bc1c6419ea3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Exit this panel and return to the product page. </value>
      <webElementGuid>054a9e96-6ab6-4046-89d9-7b1473f1dd7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-link-normal close-button</value>
      <webElementGuid>916b183c-fa71-4253-afb4-20acec448745</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>b9cf4f3b-a0cc-4620-858e-636b78096bc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;attach-close_sideSheet-link&quot;)</value>
      <webElementGuid>7ab3dc07-7109-432c-af5e-6ee97401b5a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='attach-close_sideSheet-link']</value>
      <webElementGuid>fab0d4f3-9389-4436-897c-ae8dece492c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='attach-accessory-pane']/div/div/a</value>
      <webElementGuid>48458835-5d25-4862-964b-6bcd554b23aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[95]</value>
      <webElementGuid>a3affbd5-328a-4013-90e7-ae865a343e86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div[3]/div[3]/div/div/a</value>
      <webElementGuid>73edc495-63a5-4049-92b1-35c3d2ec77d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'attach-close_sideSheet-link' and @href = '#']</value>
      <webElementGuid>4e92d574-0691-40fa-b4b2-d8af9ff5faf7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
