<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_submit.buy-now</name>
   <tag></tag>
   <elementGuidId>c7f47ed9-02dc-453d-a0a6-fe4f0d56face</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#buy-now-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='buy-now-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3156c249-77f8-4aed-b030-5c837381d488</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>buy-now-button</value>
      <webElementGuid>85b5100a-7718-469d-9c3c-1f86d79cb580</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>submit.buy-now</value>
      <webElementGuid>4d058ae7-b60a-45e2-bf7a-78fef43acf52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Buy Now</value>
      <webElementGuid>e7ff2a3a-3147-4dfc-87d0-0d872c37e55f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hover</name>
      <type>Main</type>
      <value>Select &lt;b>__dims__&lt;/b> from the left&lt;br> to Buy</value>
      <webElementGuid>3a98f0db-60d3-4d45-9933-7cc3afb491f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-input</value>
      <webElementGuid>bc6cfef4-651f-4730-8067-dd626f45a658</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>cb783c3e-e255-408c-897a-d1712550d66b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>submit.buy-now-announce</value>
      <webElementGuid>f436b1aa-7343-4b84-a6ff-8b7bb18ff835</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;buy-now-button&quot;)</value>
      <webElementGuid>eb48bbe2-11e1-4d64-bce8-f90dd4b1adda</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='buy-now-button']</value>
      <webElementGuid>02ffcbfc-22db-4b36-9eea-dff0e6ed6567</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='submit.buy-now']/span/input</value>
      <webElementGuid>69bac495-1841-4ac5-935a-4079b50531db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[41]/div/div/span/span/input</value>
      <webElementGuid>bd8afed9-16a3-486c-b9f1-f2fb4917bb0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'buy-now-button' and @name = 'submit.buy-now' and @title = 'Buy Now' and @type = 'submit']</value>
      <webElementGuid>ce46d652-c54f-41dd-a52b-fb6a85e1392f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
