<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_submit.add-to-cart</name>
   <tag></tag>
   <elementGuidId>62c048b2-5cd2-4046-8e28-d5e6c4f8d942</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='add-to-cart-button'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8ac59781-a818-4997-be30-415e22a84f55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>add-to-cart-button</value>
      <webElementGuid>fb6375ce-7c83-4609-9d5f-ee475e0f4be2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>submit.add-to-cart</value>
      <webElementGuid>0fc7d31e-3102-4b98-9e18-3164c24be959</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Add to Shopping Cart</value>
      <webElementGuid>e3fbf604-ab9a-4bb3-a273-0f85eb38cf63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hover</name>
      <type>Main</type>
      <value>Select &lt;b>__dims__&lt;/b> from the left&lt;br> to add to Shopping Cart</value>
      <webElementGuid>667328f9-3be5-4b52-b431-28f23ae5fb8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-input</value>
      <webElementGuid>e7fa682b-7d29-4df1-bff9-267e2dc90f36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>1f1506f8-04db-4558-acdc-3886a165a09b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Add to Cart</value>
      <webElementGuid>523ab00f-4170-42d2-9e30-3ab7a7df1ed3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>submit.add-to-cart-announce</value>
      <webElementGuid>38c631eb-1cf4-43fb-933a-7d1359cfb764</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formaction</name>
      <type>Main</type>
      <value>/cart/add-to-cart/ref=dp_start-bbf_1_glance</value>
      <webElementGuid>9ad38bac-4408-491b-ba69-ebd174e820c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;desktop_qualifiedBuyBox&quot;)/div[@class=&quot;a-section a-spacing-none a-padding-none&quot;]/div[@id=&quot;addToCart_feature_div&quot;]/div[@class=&quot;a-button-stack&quot;]/span[@id=&quot;atc-declarative&quot;]/span[@id=&quot;submit.add-to-cart&quot;]/span[@class=&quot;a-button-inner&quot;]/input[@id=&quot;add-to-cart-button&quot;]</value>
      <webElementGuid>736459fa-1f75-40d7-8780-5660ebd9a6b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='add-to-cart-button'])[2]</value>
      <webElementGuid>605aee27-dff6-4b06-900a-60715def7308</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//span[@id='submit.add-to-cart']/span/input)[2]</value>
      <webElementGuid>01fdb2b2-933e-424d-8da4-f25cfc36eb4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[39]/div/span/span/span/input</value>
      <webElementGuid>86b58ebc-8698-45bc-bfff-d9dd2dc3ea44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'add-to-cart-button' and @name = 'submit.add-to-cart' and @title = 'Add to Shopping Cart' and @type = 'submit']</value>
      <webElementGuid>77aa65ee-6cdd-4071-9e0c-26c5a452fdbd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
