<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Sign Out</name>
   <tag></tag>
   <elementGuidId>648db052-1e33-48ce-a9e1-9659669bf8f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nav-item-signout > span.nav-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='nav-item-signout']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c87adcf6-6178-4203-bfaf-2b2482a2617a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-text</value>
      <webElementGuid>329187c0-0e39-4d9e-aa24-a2fa7ab1de33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign Out</value>
      <webElementGuid>7c097112-68da-4f09-aaf7-0ba5489fcccb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-item-signout&quot;)/span[@class=&quot;nav-text&quot;]</value>
      <webElementGuid>756fa172-5a10-418f-93a1-daaa034f046d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='nav-item-signout']/span</value>
      <webElementGuid>02fb72cb-97c7-47ad-b50d-502a9ef48d19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[14]/span</value>
      <webElementGuid>11161546-91a7-4ce2-8afa-26c0ad12dcb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Sign Out' or . = 'Sign Out')]</value>
      <webElementGuid>0980bda5-5bad-4532-ba25-140c69d03b3f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
