<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_programs  features</name>
   <tag></tag>
   <elementGuidId>4b4e3800-d59c-47c3-9886-ca543fc851a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='hmenu-content']/ul/li[22]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8d069d64-9a81-4e63-bdbc-50c7076d2807</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmenu-item hmenu-title </value>
      <webElementGuid>e695f070-ed78-4e5c-9ebb-d696fdfc09a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>programs &amp; features</value>
      <webElementGuid>acaf153e-8207-464d-a617-d915ae5925b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hmenu-content&quot;)/ul[@class=&quot;hmenu hmenu-visible&quot;]/li[22]/div[@class=&quot;hmenu-item hmenu-title&quot;]</value>
      <webElementGuid>edec015f-bc4b-4262-8705-6df36b622705</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmenu-content']/ul/li[22]/div</value>
      <webElementGuid>4bb16ed3-57d2-4b7d-8d5a-efa756e272f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[22]/div</value>
      <webElementGuid>509b102f-c01d-493d-84b8-e87b9e56146e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'programs &amp; features' or . = 'programs &amp; features')]</value>
      <webElementGuid>97cf7025-ea06-49ce-bab8-4c90f11dd55a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
