<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Price Low to High</name>
   <tag></tag>
   <elementGuidId>8b26651a-5133-41d9-9f05-bbbbcc585dd1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#s-result-sort-select_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='s-result-sort-select_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cac4ad52-2219-4bbd-9a4d-6b60aa711dc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>e20aa692-9554-4389-bc66-f94fd7d94773</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>9344c14a-fe28-4711-a806-1ad8be3d534f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8c636144-a2eb-4203-bcc8-06476c2271be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>{&quot;stringVal&quot;:&quot;price-asc-rank&quot;}</value>
      <webElementGuid>6335b509-b204-4cff-b73c-68f195d13222</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>s-result-sort-select_1</value>
      <webElementGuid>5721f46a-7db2-40b1-9b74-64960079c5a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-dropdown-link</value>
      <webElementGuid>d2bbf829-fb8f-4239-924c-5d9ce45fe188</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Price: Low to High</value>
      <webElementGuid>5ab32543-84a5-41f9-bb13-a2deb708becf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;s-result-sort-select_1&quot;)</value>
      <webElementGuid>f471f222-4b17-4da3-9e61-1b802125f332</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='s-result-sort-select_1']</value>
      <webElementGuid>2a216352-b4d5-4721-b814-43706c36de0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='a-popover-2']/div/div/ul/li[2]/a</value>
      <webElementGuid>91196b2f-33df-4456-bc56-3f2a190b60ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Price: Low to High')]</value>
      <webElementGuid>1639a538-24c6-44f3-aed1-24a8d222c4c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[37]</value>
      <webElementGuid>2c733733-ab11-4743-bd50-efe84c9a21da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/ul/li[2]/a</value>
      <webElementGuid>5390ed4a-2dd4-4e6f-95c9-6afad1b763f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and @id = 's-result-sort-select_1' and (text() = 'Price: Low to High' or . = 'Price: Low to High')]</value>
      <webElementGuid>183c316b-cee4-48b5-91b6-55fbbeba514f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
