<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Sort byFeatured</name>
   <tag></tag>
   <elementGuidId>6801f9b3-a345-4100-abc4-9f748d96385e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#a-autoid-0-announce</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='a-autoid-0-announce']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c9035838-8d46-46e1-8fec-5420e8ad7cce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-text a-declarative</value>
      <webElementGuid>143e5879-91af-4828-92fc-0e2d05552050</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-func-deps</name>
      <type>Main</type>
      <value>aui-da-a-dropdown-button</value>
      <webElementGuid>890eac39-53f7-45fc-b9ec-0daff94109a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-type</name>
      <type>Main</type>
      <value>widget</value>
      <webElementGuid>65737e4d-2484-4041-9852-e8709144327c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-interaction-events</name>
      <type>Main</type>
      <value>click</value>
      <webElementGuid>dde21aca-4aa0-40f4-b1a8-6c339877fe7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action</name>
      <type>Main</type>
      <value>a-dropdown-button</value>
      <webElementGuid>eb8ff470-cad6-4b3e-be4a-01e1bf629e9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c5e78aef-cf1c-404f-b07f-ad0d7afa4d55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-id</name>
      <type>Main</type>
      <value>607oof-rj2qxb-kzluv0-mpn8c2</value>
      <webElementGuid>7faa7f98-e1b2-4d11-8d23-984722a46186</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>a-autoid-0-announce</value>
      <webElementGuid>fe224c7b-16aa-4f09-a090-b1d51b09c339</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sort by:Featured</value>
      <webElementGuid>90ab2b54-ff6c-4afe-8d2e-ddbc41ce4108</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a-autoid-0-announce&quot;)</value>
      <webElementGuid>630a5fc6-719f-43a6-b497-01aa1e6c78b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='a-autoid-0-announce']</value>
      <webElementGuid>45d429fd-9cf7-4f97-9b2d-189ec0ad2e68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='a-autoid-0']/span/span</value>
      <webElementGuid>236b6687-894f-42c2-a40a-52916c781be9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>b9b87cc5-c598-42b8-8936-4b7b15481733</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'a-autoid-0-announce' and (text() = 'Sort by:Featured' or . = 'Sort by:Featured')]</value>
      <webElementGuid>47c41504-667d-4d55-bd2a-bc0e5f64a2ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
